(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var x2=function(a){a.S("cardstatechange",g.sN(a)&&g.tN(a)?1:0)},lwa=function(a){var b=g.Lh(a);
a=g.Sh(a);return new g.uh(b.x,b.y,a.width,a.height)},mwa=function(a){return Math.pow(a,3)},nwa=function(a){return 3*a*a-2*a*a*a},y2=function(a,b){var c=g.xo("use_default_events_client")?void 0:g.nr;
(0,g.y)(b,function(d){d={csn:a,ve:d.getAsJson(),eventType:4};var e={Hk:g.Bs(a),kk:a};"UNDEFINED_CSN"==a?g.Ps("visualElementShown",d,e):c?g.Tp("visualElementShown",d,c,e):g.or("visualElementShown",d,e)})},z2=function(a,b){var c=g.xo("use_default_events_client")?void 0:g.nr;
(0,g.y)(b,function(d){var e=void 0,f=(e=void 0===e?!1:e)?16:8;d={csn:a,ve:d.getAsJson(),eventType:f};e={Hk:g.Bs(a),kk:a,jG:e};"UNDEFINED_CSN"==a?g.Ps("visualElementHidden",d,e):c?g.Tp("visualElementHidden",d,c,e):g.or("visualElementHidden",d,e)})},C2=function(a){a=g.Ra(a);
delete A2[a];g.Rb(A2)&&B2&&B2.stop()},pwa=function(){B2||(B2=new g.H(function(){owa()},20));
var a=B2;a.isActive()||a.start()},owa=function(){var a=(0,g.E)();
g.Cb(A2,function(b){qwa(b,a)});
g.Rb(A2)||pwa()},D2=function(a,b,c,d){g.Hn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.I=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.G=0;this.C=null},qwa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;rwa(a,a.progress);1==a.progress?(a.o=0,C2(a),a.xe(),a.Hn()):a.ub()&&a.cu()},rwa=function(a,b){g.Oa(a.F)&&(b=a.F(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.I[c]-a.A[c])*b+a.A[c]},swa=function(a,b){g.Me.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},E2=function(a,b,c,d,e){D2.call(this,b,c,d,e);
this.element=a},F2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
E2.call(this,a,b,c,d,e)},G2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},H2=function(a){return a.baseUrl||null},I2=function(a,b){return(0,g.ye)((0,g.Ic)(a,b,void 0),function(c){return!!c})},twa=function(a,b,c){function d(Ib){var kb=Ib.hovercardButton;
if(!kb)return null;kb=kb.subscribeButtonRenderer;if(!kb)return null;var te=f(kb.unsubscribedButtonText),ao=f(kb.subscribedButtonText);if(kb.subscribed){var bo=f(kb.subscriberCountWithUnsubscribeText);var co=f(kb.subscriberCountText)}else bo=f(kb.subscriberCountText),co=f(kb.subscriberCountWithSubscribeText);var Aj=null;return Ib.signinEndpoint&&(Aj=g.Mb(Ib,"signinEndpoint","webNavigationEndpointData","url"),!Aj)?null:te&&(ao||Aj)?{subscribed:kb.subscribed,subscribeText:te,subscribeCount:bo,unsubscribeText:ao,
unsubscribeCount:co,enabled:kb.enabled,signinUrl:Aj,classic:Ib.useClassicSubscribeButton}:null}
function e(Ib){if(Ib){var kb=[],te=Ib.videoId;te&&kb.push("v="+te);(te=Ib.playlistId)&&kb.push("list="+te);(Ib=Ib.startTimeSeconds)&&kb.push("t="+Ib);return"/watch?"+kb.join("&")}}
function f(Ib){if(!Ib)return null;var kb=Ib.simpleText;return kb?kb:Ib.runs?(0,g.Ic)(Ib.runs,function(te){return te.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,q=null,r=null,u=null,w=null,B=!1,z=null,D=null,F=null,G=null,V=null;if("VIDEO"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,r=f(b.videoDuration);else if("PLAYLIST"==h)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==h){if(B=g.Mb(l,"browseEndpoint","browseId"))w=B,m="/channel/"+w;n=!1;q="new";(B=!!b.isSubscribe)?z=d(b):D=f(b.subscribersText)}else"WEBSITE"==
h?((F=g.Mb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(V=f(b.additionalFeesText)),(n=g.Mb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Mb(b,"title","accessibility","accessibilityData","label");var J=b.endpoint?b.endpoint.clickTrackingParams:null,wb="";if(b.metadata){var Hb=f(b.metadata);Hb&&(wb=Hb)}return{id:"element-"+c,type:h,title:f(b.title),metadata:wb,callToAction:f(b.callToAction),
Ny:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:r,playlistLength:u,channelId:w,subscribeButton:z,subscribersText:D,isSubscribe:B,targetUrl:m,zH:n,Cc:{itct:J},ZO:q,hm:a?a:null,EH:b.isPlaceholder,impressionUrls:I2(b.impressionUrls||[],H2),rH:I2(b.hovercardShowUrls||[],H2),clickUrls:I2(l.loggingUrls||[],H2),visualElement:g.us(b.trackingParams),productPrice:G,
additionalFeesText:V}},J2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=I2(a.impressionUrls||[],H2);a.trackingParams&&(c.visualElement=g.us(a.trackingParams));c.elements=I2(a.elements||[],function(d,e){return twa(b,d,e)});
return c},K2=function(a){g.QN.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.F=this.A=null;this.M=[];a=a.O();this.N=g.py(a)||g.ry(a);this.R=!0;this.I=0;this.C=new g.ds(this);g.C(this,this.C);this.C.L(this.player,g.$y("creatorendscreen"),this.fI);this.C.L(this.player,"crx_creatorendscreen",this.gI);this.C.L(this.player,"resize",this.KA);this.C.L(window,"focus",this.TN);this.load();var b=g.se("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Je(this,function(){g.xe(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},uwa=function(a){return a.player.getVideoData().hc?"current":a.N?"new":"current"},L2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},M2=function(a,b,c){c=void 0===c?!0:c;
g.uQ(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.F.dispose(),a.F=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.M.length&&(a.M.forEach(function(l){l.dispose()}),a.M.length=0);
a.I=0;if((a.u=b)&&b.elements){c&&vwa(a);c=[];d=new g.Xy(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.U({D:"div",J:"ytp-ce-shadow"}),g.CN(a.player,a.A.element,4),a.F=new g.kO(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=wwa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.CN(a.player,f.element,4);var h=new g.Xy(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);xwa(a,f,e)}g.yN(a.player,c);
a.KA()}},vwa=function(a){var b=g.ys(),c=g.As();
c&&b&&a.u.visualElement&&g.Vs(c,b,a.u.visualElement)},wwa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",W:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:N2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:O2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Nn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-video-duration",V:b.videoDuration}]}]};
c=new g.U(c);break;case "PLAYLIST":c={D:"div",W:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-covering-image",P:N2(b)},{D:"div",J:"ytp-ce-covering-shadow-top"},{D:"a",J:"ytp-ce-covering-overlay",P:{href:O2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Nn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-playlist-count",K:[{D:"div",
J:"ytp-ce-playlist-icon"},{D:"div",J:"ytp-ce-playlist-count-text",V:b.playlistLength}]}]}]};c=new g.U(c);break;case "CHANNEL":c={D:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",W:["ytp-ce-channel-title","ytp-ce-link"],P:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Nn(b.title||"")},V:b.title},b.subscribeButton?{D:"div",J:"ytp-ce-subscribe-container",K:[{D:"div",J:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",J:"ytp-ce-channel-subscribers-text",V:b.subscribersText}:"",b.metadata?{D:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
V:b.metadata}:""]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:N2(b)}]};c=new g.U(c);var d=g.ee(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Cc.itct}else e="endscreen",f=null;e=new g.tP(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.M.push(e)}break;case "WEBSITE":c={D:"div",W:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",J:"ytp-ce-expanding-overlay-body",
K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-website-title",P:{dir:g.Nn(b.title||"")},V:b.title},{D:"div",J:"ytp-ce-website-metadata",V:b.metadata},{D:"a",W:["ytp-ce-website-goto","ytp-ce-link"],P:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:N2(b)},{D:"div",J:"ytp-ce-expanding-icon",P:ywa(b.iconUrl)}]};c=new g.U(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",J:"ytp-ce-merchandise-price-container",
K:[{D:"div",J:"ytp-ce-merchandise-price",V:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",J:"ytp-ce-merchandise-additional-fees",V:b.additionalFeesText})),c={D:"div",W:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.hm||"","aria-hidden":"true"},K:[{D:"div",J:"ytp-ce-element-shadow"},{D:"div",J:"ytp-ce-expanding-overlay",K:[{D:"div",J:"ytp-ce-expanding-overlay-hider"},{D:"div",J:"ytp-ce-expanding-overlay-background"},{D:"div",J:"ytp-ce-expanding-overlay-content",K:[{D:"div",
J:"ytp-ce-expanding-overlay-body",K:[{D:"div",J:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",J:"ytp-ce-merchandise-title",P:{dir:g.Nn(b.title||"")},V:b.title},c,{D:"div",J:"ytp-ce-merchandise-metadata",V:b.metadata},{D:"a",W:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:O2(a,b.targetUrl),target:"_blank",tabindex:"-1"},V:b.callToAction}]}]}]}]},{D:"div",J:"ytp-ce-expanding-image",P:N2(b)},{D:"div",J:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",J:"ytp-ce-merchandise-invideo-cta",
V:b.callToAction}]}]},c=new g.U(c)}b.EH&&g.I(c.element,"ytp-ce-placeholder");return c},N2=function(a){if(a.Ny)var b=a.Ny.thumbnails;
return ywa(b?b[b.length-1].url:null)},ywa=function(a){return a?{style:"background-image: url("+a+")"}:{}},xwa=function(a,b,c){function d(){h(1)}
function e(){h(-1)}
b.ma("mouseenter",(0,g.x)(a.Tu,a,b,c));b.ma("mouseleave",(0,g.x)(a.Dv,a,b,c));a.player.O().o||b.ma("click",(0,g.x)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.ma("click",(0,g.x)(a.UB,a,c));b.ma("keypress",(0,g.x)(a.UB,a,c));b.ma("focus",(0,g.x)(function(l,m){this.Tu(l,m)},a,b,c));
b.ma("blur",(0,g.x)(function(l,m){this.Dv(l,m)},a,b,c));
b.ma("touchstart",(0,g.x)(a.Tu,a,b,c));var f=g.ge("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Fn(b.element,"ytp-ce-element-hover");g.Fn(b.element,"ytp-ce-force-expand")});
b.ma("keydown",(0,g.x)(function(l,m){this.R=9==m.keyCode&&!m.shiftKey},a,b));
var h=(0,g.x)(function(l,m,n){this.I+=n;0<this.I?(g.I(l.element,"ytp-ce-force-expand"),P2(this,m.id,!0)):(g.Fn(l.element,"ytp-ce-force-expand"),g.Fn(l.element,"ytp-ce-element-hover"),P2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ma("blur",g.Sa(function(){"none"!=m.style.display&&a.R&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.ge("ytp-sb-subscribe",b.element));c(g.ge("ytp-sb-unsubscribe",b.element));b.ma("focus",d);b.ma("blur",e)},O2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.Vy(c)+b}else return"";return b},P2=function(a,b,c){a.A&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.K(a.o[d].element,"ytp-ce-element-shadow-show",c)},Q2=function(a,b,c){function d(){f||(e++,e==b.length&&(h.stop(),c&&c()))}
if(!b||0==b.length||L2(a))c&&c();else{b=zwa(a,b);var e=0,f=!1,h=new g.H(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Br(b[a],d)}},R2=function(a,b,c){Q2(a,b.clickUrls,c);
(a=g.As())&&b.zH&&g.Ws(a,b.visualElement)},zwa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Awa(b[e],c));return d},Awa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Bwa=function(a){return Array.isArray(a)&&a.length?a[0]:a},S2=function(a){return"string"===typeof a?a:""},T2=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Cwa=function(a){this.externalId=a},Dwa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},U2=function(a){return a.value?a.value:null},V2=function(a){if(!a)return null;
var b=g.Dc(S2(a.value));b=g.zc(b);if(!b)return null;var c=T2(a.target,Ewa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Dwa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Fwa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Iwa=function(a){if(!a)return null;
var b=T2(a.type,Gwa),c=T2(a.trigger,Hwa),d=Bwa(a.url);d=V2(d?d:null);a=Bwa(a.subscribeData);var e=a?a:null;e?(a=S2(e.external_user_id),e=S2(e.subscription_token),a=a&&e?new Cwa(a):null):a=null;return b?new Fwa(b,c,d,a):null},W2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Jwa=function(a,b){return g.cb(a.action,b,void 0)},Kwa=function(a,b){this.context=a;
this.o=b},Y2=function(a){return a.customMessage?X2("div","iv-card-message",a.customMessage):""},Z2=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",J:"iv-card-image",P:{style:c},K:d}},$2=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.p(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(X2("li","",c.value));return{D:"ul",J:"iv-card-meta-info",K:b}},X2=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Nn(c);return{D:a,P:b,V:c}},Lwa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Zo&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Zo+");");c.dir=g.Nn(a.customMessage);var d=[{D:"span",V:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",J:"iv-card-link-icon"}));return{D:"div",W:b,P:c,K:d}},a3=function(a,b,c,d){if(d){b=g.p(b);
for(var e=b.next();!e.done;e=b.next())a.o(e.value,d,c.id,c.Cc,c.be.click,5)}},Mwa=function(a,b){this.merchant=a;
this.price=b},Nwa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Owa=function(a,b){return b?b:Nwa(a)?"current":"new"},b3=function(a,b){g.A.call(this);
var c=this;this.element=a;this.context=b;this.sa=!1;this.ga=new Map;this.fa=new Map;this.context.H.addEventListener(g.$y("annotations_module"),function(d){(d=c.ga.get(d))&&d.apply(c)});
this.context.H.addEventListener("crx_annotations_module",function(d){(d=c.fa.get(d))&&d.apply(c)})},c3=function(a,b,c,d,e,f,h){a.context.o.ma(b,"click",function(){a.Yu(c,d,e,f||[],h||0)});
a.context.o.ma(b,"touchstart",function(){a.sa=!1});
a.context.o.ma(b,"touchmove",function(){a.sa=!0})},Pwa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},d3=function(a,b,c){return{Vz:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
OD:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Xr:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},g3=function(a,b,c){b3.call(this,b,c);
var d=this;this.H=a;this.eventId=null;this.Z=this.Ea=this.A=this.Ic=!1;this.aa=null;this.cards=[];this.va=this.I=this.Y=this.C=this.da=this.o=null;this.N=[];this.G=this.zc=this.T=null;this.F=0;this.U=new g.H(g.Ka,c.B.ib?4E3:3E3);g.C(this,this.U);this.na=new g.H(g.Ka);g.C(this,this.na);this.R=new Kwa(c,function(e,f,h,l,m,n){c3(d,e,f,h,l,m,n)});
this.M=new g.U({D:"div",J:"iv-drawer",P:{id:"iv-drawer"},K:[{D:"div",J:"iv-drawer-header",P:{"aria-role":"heading"},K:[{D:"span",J:"iv-drawer-header-text"},{D:"button",W:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",J:"iv-drawer-content"}]});g.C(this,this.M);this.B=this.M.element;this.ra=new g.kO(this.M,330);g.C(this,this.ra);this.ya=g.ge("iv-drawer-header-text",this.B);this.u=g.ge("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ea&&e3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ea=d.A)&&f3(d)})},Qwa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){e3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){f3(a)});
var d=c.headerText;g.Be(a.ya,d);a.I&&a.I.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.T=g.us(c.trackingParams);a.G=g.us(c.closeTrackingParams);a.zc=g.us(c.iconTrackingParams)},Rwa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.F;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"simple",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:h3(a,c,b,d),sponsored:!1,be:d3(d,e,d.command),dh:d.trackingParams?g.us(d.trackingParams):null,tf:e.trackingParams?g.us(e.trackingParams):
null,zc:f&&f.trackingParams?g.us(f.trackingParams):null,imageUrl:i3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Zo:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?V2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.command.urlEndpoint.url}):null};j3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.collaboratorInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:h3(a,c,b,d),sponsored:!1,be:d3(d,e,d.endpoint),dh:d.trackingParams?g.us(d.trackingParams):null,tf:e.trackingParams?g.us(e.trackingParams):null,zc:f&&f.trackingParams?g.us(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,
customMessage:d.customText?g.S(d.customText):null,SC:i3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:V2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};j3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:h3(a,c,b,d),sponsored:!1,be:d3(d,e,d.action),dh:d.trackingParams?g.us(d.trackingParams):null,tf:e.trackingParams?g.us(e.trackingParams):null,zc:f&&f.trackingParams?g.us(f.trackingParams):null,no:i3(d.playlistThumbnail.thumbnails,
258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:V2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Pwa(d.action)})};j3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?
b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.F,type:"video",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Cc:h3(a,c,b,d),sponsored:!1,be:d3(d,e,d.action),dh:d.trackingParams?g.us(d.trackingParams):null,tf:e.trackingParams?g.us(e.trackingParams):null,zc:f&&f.trackingParams?g.us(f.trackingParams):null,no:i3(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.S(d.lengthString):
null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:V2({pause_on_navigation:!a.context.videoData.wa,target:"new",value:Pwa(d.action)})};j3(a,c)}a.F++},i3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},h3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},Twa=function(a,b){var c=Swa(a,b);
c&&(c===a.o&&(a.o=null),a.H.removeCueRange(c.card.id),g.xe(c.ht),g.lb(a.cards,c),a.ep(),k3(a))},e3=function(a,b,c){if(!a.A){a.ra.show();
a.da=new g.H(function(){g.I(a.context.H.getRootNode(),g.bM.IV_DRAWER_OPEN)},0);
a.da.start();a.aa=g.dp(a.u,"mousewheel",function(h){a.U.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.A=!0;var d=g.As();d&&a.T&&a.G&&y2(d,[a.T,a.G]);b={TRIGGER_TYPE:b};for(var e=g.p(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.vA||(f.vA=!0,Uwa(a.context.logger,f.card.be.Vz,b)),d&&y2(d,[f.card.dh]);x2(a.H);c&&(a.C=new g.H(function(){a.Y=a.I;a.va.focus()},330),a.C.start())}},f3=function(a){a.A&&(a.ra.hide(),g.ep(a.aa),a.aa=null,g.Fn(a.context.H.getRootNode(),g.bM.IV_DRAWER_OPEN),a.A=!1,x2(a.H),a.C&&a.C.stop(),a.C=new g.H(function(){a.Y&&(a.Y.focus(),a.Y=null)},330),a.C.start())},Wwa=function(a){g.En(a.xa(),
[g.bM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.CN(a.H,a.B,5);Vwa(a);a.I=g.ge("ytp-cards-button",a.H.getRootNode());a.va=g.ge("iv-drawer-close-button",a.B);a.Ic=!0},Vwa=function(a){var b=g.ge("iv-drawer-close-button",a.B);
a.context.o.ma(b,"click",a.QF,a);a.context.o.ma(a.u,"touchend",function(){a.U.start()});
a.context.o.ma(a.u,"scroll",a.hG,a);a.context.u.subscribe("onHideControls",function(){a.Z=!0});
a.context.u.subscribe("onShowControls",function(){a.Z=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Z=g.Dn(a.H.getRootNode(),"ytp-autohide")});
a.N.push(g.Oo("iv-button-shown",a.JH,a));a.N.push(g.Oo("iv-button-hidden",a.IH,a));a.N.push(g.Oo("iv-teaser-shown",a.SI,a));a.N.push(g.Oo("iv-teaser-hidden",a.KH,a));a.N.push(g.Oo("iv-teaser-clicked",a.RI,a))},j3=function(a,b){a.Ic||Wwa(a);
Twa(a,b.id);var c=Xwa(a,b);if(c){var d={card:b,ht:c.element,vA:!1},e=Ywa(a,d);g.sb(a.cards,e,0,d);c.ba(a.u,e);a.ep();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.A||(a.o=d,k3(a),Zwa(a,d),e3(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.H.getCurrentTime(),5E3>c&&c>b.startMs&&$wa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){$wa(a,d)}),k3(a))}},Xwa=function(a,b){switch(b.type){case "simple":var c=a.R;
var d=b.displayDomain?{D:"div",J:"iv-card-image-text",V:b.displayDomain}:void 0;var e=Lwa(b);d={D:"div",W:["iv-card"],K:[{D:"a",J:"iv-click-target",P:{href:b.url?U2(b.url)||"":""},K:[Z2(b.imageUrl,d),{D:"div",J:"iv-card-content",K:[X2("h2",void 0,b.title),e]}]}]};d=new g.U(d);a3(c,g.fe("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.R,d={D:"div",W:["iv-card","iv-card-channel"],K:[{D:"a",W:["iv-click-target"],P:{href:U2(b.url)||"","data-ytid":b.channelId},K:[Z2(b.SC),
{D:"div",J:"iv-card-content",K:[Y2(b),{D:"h2",J:"iv-card-primary-link",V:b.title},$2(b)]}]}]},d=new g.U(d),a3(c,g.fe("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.R,d={D:"div",W:["iv-card","iv-card-playlist"],K:[{D:"a",J:"iv-click-target",P:{href:U2(b.url)||""},K:[Z2(b.no,{D:"div",J:"iv-card-image-overlay",K:[{D:"span",J:"iv-card-playlist-video-count",V:b.playlistVideoCount}]}),{D:"div",J:"iv-card-content",K:[Y2(b),X2("h2","iv-card-primary-link",b.title),$2(b)]}]}]},d=new g.U(d),
a3(c,g.fe("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.R;var f=!g.gb(b.offers);d=["iv-card"];e="";var h=Lwa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({D:"div",J:"iv-card-offer-price",V:h.price}),h.merchant&&f.push({D:"div",J:"iv-card-offer-merchant",V:h.merchant}),h={D:"div",K:f});f=b.url?U2(b.url)||"":"";d={D:"div",W:d,P:{tabindex:"0"},K:[{D:"a",W:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{D:"div",J:"iv-card-content",K:[b.sponsored?{D:"div",J:"iv-card-sponsored",K:["Sponsored",{D:"div",J:"iv-ad-info-container",K:[{D:"div",J:"iv-ad-info",V:"{{adInfo}}"},{D:"div",J:"iv-ad-info-icon-container",K:[{D:"div",J:"iv-ad-info-icon"},{D:"div",J:"iv-ad-info-callout"}]}]}]}:"",{D:"a",J:"iv-click-target",P:{href:f},K:[X2("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.se("span");g.Be(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Db(e,"adInfo");a3(c,g.fe("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.R,d=b.isLiveNow?{D:"span",W:["yt-badge","yt-badge-live"],V:"LIVE NOW"}:null,d={D:"div",W:["iv-card","iv-card-video"],K:[{D:"a",J:"iv-click-target",P:{href:U2(b.url)||""},K:[Z2(b.no,b.videoDuration?{D:"span",J:"iv-card-video-duration",V:b.videoDuration}:void 0),{D:"div",J:"iv-card-content",K:[Y2(b),X2("h2","iv-card-primary-link",b.title),$2(b),d]}]}]},d=new g.U(d),a3(c,g.fe("iv-click-target",d.element),
b,b.url),d;default:return null}},Ywa=function(a,b){if(0===a.cards.length)return 0;
var c=g.db(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},axa=function(a){return a.o?"productListing"===a.o.card.type:(0,g.yi)(a.cards,function(b){return"productListing"===b.card.type})},k3=function(a){g.K(a.H.getRootNode(),"ytp-cards-shopping-active",axa(a))},$wa=function(a,b){if(!g.Dn(a.H.getRootNode(),"ytp-cards-teaser-shown")){if(a.o!==b){var c=g.As(),d=a.o?a.o.card.zc:a.zc;
c&&d&&z2(c,[d]);a.o=b;k3(a)}if(c="none"!=a.xa().style.display)2===a.context.H.getPresentingPlayerType()?c=1===a.context.H.getAdState():(c=a.context.H.getPlayerState(),d=0===c&&0===a.context.H.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&(c={teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs},(d=g.rN(g.gN(a.H)))&&d.Ru(!0,c));a.na.isActive()||((!a.A||!a.U.isActive()&&a.Z)&&Zwa(a,b),a.na.start(910+b.card.teaserDurationMs))}},Zwa=function(a,b){if(a.M.La()){var c=new D2([0,
a.u.scrollTop],[0,b.ht.offsetTop],600,nwa);a.context.A.ma(c,"animate",function(d){a.u.scrollTop=d.y});
a.context.A.ma(c,"finish",function(d){a.u.scrollTop=d.y});
c.play()}else g.aM(a.M,!0),a.u.scrollTop=b.ht.offsetTop,g.aM(a.M,!1)},l3=function(a){return a.o&&a.o.card?a.o.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},Swa=function(a,b){return g.cb(a.cards,function(c){return c.card.id===b})},m3=function(a,b,c){b3.call(this,a,b);
this.annotation=c;this.isActive=!1},bxa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},n3=function(a,b,c){m3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},cxa=function(a,b){var c=void 0===c?0:c;
var d=lwa(b).width;g.Hh(b,d);c=new F2(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,mwa);g.C(a,c);a.context.A.ma(c,"begin",function(){g.Th(b,!0)});
c.play()},fxa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
W:["iv-branding-context-name"],V:b.channel_name}),d=a.createElement({D:"div",W:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.o=new g.tP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.H),a.o.ba(d));var f=a.createElement({D:"div",W:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",W:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Th(h,!1);var l=a.createElement({D:"div",W:["branding-context-container-outer"]});l.appendChild(h);g.zh(l,"right",b.image_width+"px");a.xa().appendChild(l);a.A=new g.H(function(){dxa(a,h,l)},500);
g.C(a,a.A);a.context.o.ma(a.xa(),"mouseover",function(){exa(a,h,l,f,b.image_height)});
a.context.o.ma(a.xa(),"mouseout",function(){a.A.start()})}},exa=function(a,b,c,d,e){a.A.stop();
if(!a.B){var f=g.Sh(b);a.o||(g.Qh(b,f.width),g.Qh(c,f.width));g.zh(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.zh(d,"right","1px");a.B=!0;g.Th(b,!0);a.C=new g.H(function(){g.I(this.xa(),"iv-branding-active")},0,a);
a.C.start()}},dxa=function(a,b,c){g.Fn(a.xa(),"iv-branding-active");
a.F=new g.H(function(){g.Th(b,!1);a.o||g.Qh(c,0)},250);
a.F.start();a.B=!1},gxa=function(a,b,c,d,e,f,h){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.H=f;this.u=h},o3=function(a,b,c){m3.call(this,a,b,c);
var d=this;this.I=this.isCollapsed=this.M=!1;this.F=5E3;this.u=this.A=this.o=this.B=null;this.G=this.createElement({D:"div",W:["iv-promo-contents"]});this.C=new g.H(function(){d.o.setAttribute("aria-hidden","true");g.Th(d.A,!1);g.Th(d.u,!0)},700,this);
g.C(this,this.C)},hxa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.F=b.collapsedelay_ms||a.F;var d=["iv-promo","iv-promo-inactive"];a.xa().setAttribute("aria-hidden","true");a.xa().setAttribute("aria-label","Promotion");a.xa().tabIndex=0;var e=a.annotation.yc(),f=b.image_url;if(f){var h=a.createElement({D:"div",W:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",P:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?
(f=a.createElement({D:"span",J:"iv-promo-video-duration",V:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",J:"iv-promo-playlist-length",V:b.playlist_length.toString()}),h.appendChild(f));e&&c3(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",J:"iv-promo-txt"}),g.ad(f,U2(e)),a.o=f):a.o=a.createElement({D:"div",J:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",K:[{D:"strong",V:b.text_line_1}]});
var m=a.createElement({D:"p",K:[{D:"span",J:"iv-promo-link",V:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",W:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",W:["iv-button","iv-promo-button"],K:[{D:"span",J:"iv-button-content",V:f}]});var q=a.createElement({D:"div",J:"iv-promo-button-container"});q.appendChild(f);e&&c3(a,a.xa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&
c3(a,a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",K:[{D:"span",V:b.text_line_1}]}),m=a.createElement({D:"p",K:[{D:"strong",V:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",W:["yt-badge","iv-promo-badge-live"],V:"LIVE NOW"})),g.I(a.o,"iv-click-target"),e&&c3(a,a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.G.appendChild(a.o);q&&a.G.appendChild(q);c=a.createElement({D:"div",
J:"iv-promo-actions"});a.u=a.createElement({D:"button",W:["iv-promo-expand","ytp-button"]});a.u.title="Expand";a.context.o.ma(a.u,"click",function(r){p3(a,5E3,r)});
c.appendChild(a.u);g.Th(a.u,!1);a.context.o.ma(a.xa(),"mouseover",a.ZG,a);a.context.o.ma(a.xa(),"mouseout",a.YG,a);a.context.o.ma(a.xa(),"touchend",function(r){p3(a,5E3,r)});
a.A=a.createElement({D:"button",W:["iv-promo-close","ytp-button"]});a.A.title="Close";a.context.o.ma(a.A,"click","cta"===a.annotation.style&&b.text_line_3?a.SG:a.QG,a);c.appendChild(a.A);g.En(a.xa(),d);h&&(a.xa().appendChild(h),n&&h.appendChild(n));a.xa().appendChild(a.G);a.xa().appendChild(c)},p3=function(a,b,c){c.stopPropagation();
ixa(a);jxa(a,b);a.o.focus()},kxa=function(a){a.isCollapsed||a.I||a.B||(g.I(a.xa(),"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},ixa=function(a){a.C.stop();
a.isCollapsed&&(g.Gn(a.xa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Th(a.u,!1),g.Th(a.A,!0))},jxa=function(a,b){a.B||(a.B=g.Yf(function(){q3(this);
kxa(this)},b,a))},q3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},lxa=function(a){this.H=a},Uwa=function(a,b,c){b&&(c?r3(a,b.map(function(d){return g.jn(d,c)})):r3(a,b))},r3=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.p(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Br(m,f);d&&(e++,0!==d&&a.H.sendVideoStatsEngageEvent(d,f))},s3=function(a){g.QN.call(this,a);
var b=this;this.M=!1;this.loadNumber=0;this.G={};this.logger=new lxa(this.player);this.C=new g.ds(this);this.F=this.A=null;this.events=new g.ds(this);this.I=this.o=null;this.N=[];g.C(this,this.C);this.C.L(this.player,"onVideoAreaChange",function(){b.S("onVideoAreaChange")});
this.C.L(this.player,"onHideControls",function(){b.S("onHideControls")});
this.C.L(this.player,"onShowControls",function(){b.S("onShowControls")});
this.C.L(this.player,"resize",function(d){b.S("resize",d)});
this.C.L(this.player,"presentingplayerstatechange",function(d){b.S("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.QI,this);this.subscribe("resize",this.rr,this);this.player.O().N.subscribe("vast_info_card_add",this.DC,this);g.C(this,this.events);this.R=this.createElement({D:"div",J:"video-custom-annotations"});this.u=new g.U({D:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.u);g.CN(this.player,this.u.element,4);this.u.hide();this.B=new g.U({D:"div",W:["ytp-iv-video-content"]});g.C(this,this.B);a=this.createElement({D:"div",J:"video-annotations"});
a.appendChild(this.R);this.B.element.appendChild(a);mxa(this)&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.Je(this,function(){g.xe(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},nxa=function(a){a=a.createElement({D:"div",
W:["annotation","annotation-type-custom"]});g.Th(a,!1);return a},mxa=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1===(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.tE||b.N.get(a.videoId)||g.XB(a)||g.YB(a)?!0:!1},oxa=function(a,b){var c=!b.isCued()&&!g.T(b,1024);
g.aM(a.u,c);g.aM(a.B,c)},pxa=function(a,b,c){a.M=!0;
a.F=g.rq(b,c)},qxa=function(a,b){for(var c={},d=g.p(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(qxa(a,e))}return c},txa=function(a){var b=a.player.getVideoData();
if(b.af){var c=a.player.O().N.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.lq(h)&&h.responseXML?h.responseXML:null)&&t3(a,h)}};
g.tp()&&(d.onFinish=rxa(a,d.onFinish));d.postParams={ic_only:"1"};sxa(d,c);a.M=!0;g.rq(b.af,d)}}},sxa=function(a,b){a.method="POST";
a.Gb=a.Gb||{};b.jp&&(a.Gb.ic_coll=b.jp);b.kp&&(a.Gb.ic_xml=b.kp);b.ro&&(a.Gb.ic_track=b.ro)},uxa=function(a){var b=new g.U({D:"div"});
g.Th(b.element,!1);var c=new g3(a.player,b.element,u3(a));g.C(c,b);b.ba(a.u.element);c.bo();return c},u3=function(a){if(!a.I){var b=new G2(a);
g.C(a,b);var c=new g.x1(a);g.C(a,c);a.I=new gxa(b,c,a.player.O(),a.player.getVideoData(),a.logger,a.player,a.Ea)}return a.I},t3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.As();if(e){var f=g.ys();f&&g.Qs(g.xo("use_default_events_client")?void 0:g.nr,e,f,[g.us(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=qxa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=T2(h.type,vxa),r=T2(h.style,wxa),u=S2(h.data),w=0!==u.length?JSON.parse(u):{};var B=h.action;h=Iwa;if(null==B)var z=null;else if(g.Na(B)){m=[];for(var D=g.p(B),F=D.next();!F.done;F=
D.next()){var G=h(F.value);G&&m.push(G)}z=m}else{var V=h(B);z=V?[V]:[]}f=n&&q?new W2(n,q,r,z,w):null}else f=null}catch(te){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var J=nxa(h),wb=null;switch(m.type){case "branding":if(h.player.O().Ha)break;h.u.element.appendChild(J);wb=new n3(J,u3(h),m);break;case "promotion":g.CN(h.player,J,4),wb=new o3(J,u3(h),m)}wb&&wb.bo();if(h=wb)g.C(a,h),a.G[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.o||(a.o=uxa(a),g.C(a,a.o));if("card"===f.type){c=
a.o;var Hb=f&&f.data&&f.data.card_type;h=f.data;if(Hb)switch(m=h.tracking||{},m={Vz:m.impression,click:m.click,close:m.close,OD:m.teaser_impression,Xr:m.teaser_click},J=h.tracking_params||{},wb=null,Hb){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,be:m,dh:J.card?g.us(J.card):null,tf:J.teaser?g.us(J.teaser):null,zc:J.icon?
g.us(J.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,SC:h.image_url,title:h.title,metaInfo:h.meta_info,url:V2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};j3(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,be:m,dh:J.card?g.us(J.card):null,
tf:J.teaser?g.us(J.teaser):null,zc:J.icon?g.us(J.icon):null,no:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:V2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};j3(c,f);break;case "productListing":h.signin_url&&(wb=V2({target:"current",value:h.signin_url}));Hb=[];for(var Ib=h.offers||[],kb=0;kb<Ib.length;kb++)Hb.push(new Mwa(g.id(Ib[kb].merchant),g.id(Ib[kb].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,be:m,dh:J.card?g.us(J.card):null,tf:J.teaser?g.us(J.teaser):null,zc:J.icon?g.us(J.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Zo:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:V2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),tU:wb,sU:h.signin_title?h.signin_title:void 0,rU:h.signin_message?h.signin_message:void 0,offers:Hb};j3(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,be:m,dh:J.card?g.us(J.card):null,tf:J.teaser?g.us(J.teaser):null,zc:J.icon?
g.us(J.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,Zo:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:V2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};j3(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Cc:h.session_data||{},sponsored:h.sponsored||!1,be:m,dh:J.card?g.us(J.card):null,tf:J.teaser?g.us(J.teaser):null,zc:J.icon?g.us(J.icon):null,no:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:V2({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},j3(c,f)}}else Qwa(a.o,f);c=!0}}c&&(x2(a.player),a.rr())},xxa=function(a,b){var c=!1;
a.o||(a.o=uxa(a),g.C(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Rwa(a.o,e.cardRenderer),c=!0);c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.Be(c.ya,d),c.I&&c.I.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.T=b.trackingParams?g.us(b.trackingParams):null,c.G=b.closeButton.infoCardIconRenderer.trackingParams?g.us(b.closeButton.infoCardIconRenderer.trackingParams):null,c.zc=b.icon.infoCardIconRenderer.trackingParams?
g.us(b.icon.infoCardIconRenderer.trackingParams):null,x2(a.player),a.rr())},yxa=function(a,b,c,d,e){if(!a.player.O().Ha){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Fwa("openUrl","click",new Dwa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new W2(c,"branding","branding",f,d);d=nxa(a);a.u.element.appendChild(d);f=new n3(d,u3(a),f);f.bo();g.C(f,f);a.G[c]=f}},rxa=function(a,b){return function(c){for(var d=
[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.ha()||(d.unshift(b),b=g.Sa.apply(window,d),a.N.push(g.rp(b)))}},zxa=function(a){return"annotation-editor"===a||"live-dashboard"===a},A2={},B2=null;g.Ua(D2,g.Hn);g.k=D2.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.ub())return!1;C2(this);this.startTime=a=(0,g.E)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.mr();this.bf("play");-1==this.o&&this.bf("resume");this.o=1;var b=g.Ra(this);b in A2||(A2[b]=this);pwa();qwa(this,a);return!0};
g.k.stop=function(a){C2(this);this.o=0;a&&(this.progress=1);rwa(this,this.progress);this.bf("stop");this.Hn()};
g.k.pause=function(){this.ub()&&(C2(this),this.o=-1,this.bf("pause"))};
g.k.X=function(){0==this.o||this.stop(!1);this.bf("destroy");D2.uc.X.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.cu=function(){this.bf("animate")};
g.k.bf=function(a){this.dispatchEvent(new swa(a,this))};
g.Ua(swa,g.Me);g.Ua(E2,D2);E2.prototype.B=g.Ka;E2.prototype.cu=function(){this.B();E2.uc.cu.call(this)};
E2.prototype.Hn=function(){this.B();E2.uc.Hn.call(this)};
E2.prototype.mr=function(){this.B();E2.uc.mr.call(this)};
g.Ua(F2,E2);F2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.t(G2,g.A);G2.prototype.ma=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.dp(a,b,c);this.o.push(a);return a};
G2.prototype.Lu=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.mp(a,b,c);this.o.push(a);return a};
G2.prototype.rb=function(a){g.ep(a);g.lb(this.o,a)};
G2.prototype.X=function(){g.ep(this.o);this.o.length=0;g.A.prototype.X.call(this)};g.t(K2,g.QN);g.k=K2.prototype;g.k.load=function(){g.QN.prototype.load.call(this);if(!L2(this)){var a=g.WB(this.player.getVideoData());if(a)a=J2(a,uwa(this)),M2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",xe:(0,g.x)(this.uL,this,a),vf:{v:a},withCredentials:!0};this.N&&(a.vf.ptype="embedded");var c=this.player.getVideoData().Ap;c&&(a.Gb={ad_tracking:c});if(b=g.VB(b))if(b=g.Dc(b),b=g.zc(b))this.B=g.rq(b,a)}}};
g.k.unload=function(){M2(this,null);this.B&&(this.B.abort(),this.B=null);g.QN.prototype.unload.call(this)};
g.k.hd=function(a,b){if(!L2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=J2(b,"new");M2(this,c);return!0}return null};
g.k.getOptions=function(){return L2(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.uL=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=J2(c,uwa(this)))}M2(this,c)};
g.k.KA=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Axa.length;f++){var h=Math.abs(b.width-Axa[f]);if(-1==e||d>=h)e=f,d=h}d=Bxa[e];this.A&&g.zh(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Rh(e.element,Math.round(h.width*a.width),f);g.Hh(e.element,m,n);g.Gn(e.element,Cxa);m=h.left+h.width/2;h=h.top+l/2;g.I(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Gn(e.element,Bxa);g.I(e.element,d);(e=g.ee(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.zh(e,"height",f+"px")}}}}};
g.k.fI=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())Q2(this,this.u.impressionUrls),(a=g.As())&&this.u.visualElement&&g.Rs(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");Q2(this,c.impressionUrls);(b=g.As())&&g.Rs(b,c.visualElement);this.player.O().A&&this.player.oa("endscreenelementshown",a)}};
g.k.gI=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Fn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Fn(b,"ytp-ce-shown");this.player.O().A&&this.player.oa("endscreenelementhidden",a)}};
g.k.TN=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.Gn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.UB=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Dn(c,"ytp-ce-element");){g.Dn(c,"subscribe-label")&&R2(this,a);if(g.Dn(c,"ytp-ce-channel-subscribe"))return;c=g.ze(c)}if(!c||g.Dn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Dv(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.ZO?(R2(this,a),this.zD(),this.player.pauseVideo(),c=g.Dc(O2(this,a.targetUrl)),c=g.zc(c),g.rO(c,void 0,a.Cc)):(c=this.player.getVideoData().hc,
c=(0,g.x)(this.SO,this,c,O2(this,a.targetUrl),a.Cc),c=(0,g.x)(this.zD,this,c),R2(this,a,c))}}};
g.k.SO=function(a,b,c){var d=g.$p(b);a&&d&&(d.v||d.list)?g.xU(this.player.app,d.v,c,d.list,!1,void 0):g.qO(b,c)};
g.k.Tu=function(a,b){g.Dn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.H(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),Q2(this,b.rH),P2(this,b.id,!0))};
g.k.Dv=function(a,b){g.Fn(a.element,"ytp-ce-element-hover");g.Fn(a.element,"ytp-ce-force-expand");P2(this,b.id,!1)};
g.k.zD=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Axa=[346,426,470,506,570,640,853,1280,1920],Bxa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Cxa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Ewa={JQ:"current",gS:"new"};var Gwa={CLOSE:"close",kS:"openUrl",oF:"subscribe"},Hwa={zQ:"click",CLOSE:"close",rR:"hidden",VS:"rollOut",WS:"rollOver",cT:"shown"};W2.prototype.yc=function(){var a=Jwa(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var wxa={hQ:"anchored",KE:"branding",CHANNEL:"channel",IQ:"cta",uR:"highlightText",JR:"label",PLAYLIST:"playlist",HS:"popup",iT:"speech",oF:"subscribe",uT:"title",VIDEO:"video",HT:"website"},vxa={KE:"branding",rQ:"card",OQ:"drawer",tR:"highlight",UR:"marker",MS:"promotion",TEXT:"text",JT:"widget"};g.t(b3,g.A);g.k=b3.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Xy(a,b,{id:c});a.namespace="annotations_module";d&&this.ga.set(a,d);e&&this.fa.set(a,e);g.yN(this.context.H,[a])};
g.k.bo=function(){this.context.u.subscribe("resize",this.ep,this)};
g.k.xa=function(){return this.element};
g.k.Yu=function(a,b,c,d,e,f){if(this.sa)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.xe(this.xa())};
g.k.ep=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=U2(a);if(f){var h=Owa(f,a.target),l=function(){a.o&&e.context.H.pauseVideo();var m=e.context.videoData.hc||!1,n=g.$p(f||"");m&&n&&(n.v||n.list)?g.xU(e.context.H.app,n.v,b,n.list,!1,void 0):g.rO(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);r3(this.context.logger,c,l,d);Nwa(f)||(c=g.As(),d=b.itct,c&&d&&g.Ws(c,g.us(d)))}};
g.k.X=function(){this.ga.clear();this.fa.clear();g.A.prototype.X.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.C(this,a);return a.element};g.t(g3,b3);g.k=g3.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.H.getRootNode())?(a=g.Sh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.ep=function(){var a=this.isAvailable();g.Th(this.xa(),a);g.K(this.context.H.getRootNode(),g.bM.IV_DRAWER_ENABLED,a);x2(this.H)};
g.k.destroy=function(){var a=g.rN(g.gN(this.H));a&&a.Ru(!1,void 0);try{this.H.getRootNode().removeChild(this.B)}catch(b){}g.Po(this.N);g.ep(this.aa);this.da&&this.da.dispose();this.C&&this.C.dispose();b3.prototype.destroy.call(this)};
g.k.QF=function(){if(this.A){r3(this.context.logger,l3(this).be.close);var a=g.As();a&&this.G&&g.Ws(a,this.G);f3(this)}};
g.k.hG=function(){g.K(this.B,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.JH=function(){var a=g.As(),b=l3(this);b=b?b.zc:this.zc;a&&b&&y2(a,[b])};
g.k.IH=function(){var a=g.As(),b=l3(this);b=b?b.zc:this.zc;a&&b&&z2(a,[b])};
g.k.SI=function(){var a=l3(this);r3(this.context.logger,a.be.OD);var b=g.As();b&&a&&y2(b,[a.tf,a.zc])};
g.k.KH=function(){var a=g.As(),b=l3(this);a&&b&&z2(a,[b.tf])};
g.k.RI=function(a){var b=l3(this),c=g.As();this.o?a?(a=this.context.logger,r3(a,b.be.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&b.tf&&g.Ws(c,b.tf)):(a=this.context.logger,r3(a,b.be.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&b.zc&&g.Ws(c,b.zc)):(a=this.context.logger,r3(a,b.be.Xr),a.H.sendVideoStatsEngageEvent(4,void 0),c&&this.zc&&g.Ws(c,this.zc))};g.t(m3,b3);m3.prototype.bo=function(){b3.prototype.bo.call(this);bxa(this)};
m3.prototype.show=function(){b3.prototype.show.call(this);var a=g.As(),b=this.annotation.data;a&&b&&(b=b.session_data)&&y2(a,[g.us(b.itct)])};
m3.prototype.hide=function(){b3.prototype.hide.call(this);var a=g.As(),b=this.annotation.data;a&&b&&(b=b.session_data)&&z2(a,[g.us(b.itct)])};g.t(n3,m3);
n3.prototype.show=function(){if(!this.isActive){m3.prototype.show.call(this);if(!this.G){g.I(this.xa(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({D:"img",W:["branding-img","iv-click-target"],P:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Th(this.u,!1);var b=this.createElement({D:"div",W:["branding-img-container"]});b.appendChild(this.u);this.xa().appendChild(b);(b=this.annotation.yc())&&c3(this,this.u,b,this.annotation.id,a.session_data);
fxa(this,a);this.G=!0}g.Th(this.xa(),!0);this.isActive=!0;this.u&&cxa(this,this.u)}};
n3.prototype.hide=function(){this.isActive&&(m3.prototype.hide.call(this),g.Th(this.xa(),!1),this.isActive=!1)};
n3.prototype.destroy=function(){this.o&&(this.o.dispose(),this.o=null);m3.prototype.destroy.call(this)};g.t(o3,m3);g.k=o3.prototype;g.k.show=function(){this.isActive||(m3.prototype.show.call(this),this.M||(hxa(this),this.M=!0),g.Th(this.xa(),!0),g.Yf(function(){g.Fn(this.xa(),"iv-promo-inactive")},100,this),this.xa().removeAttribute("aria-hidden"),this.isActive=!0,q3(this),ixa(this),jxa(this,this.F))};
g.k.hide=function(){this.isActive&&(g.I(this.xa(),"iv-promo-inactive"),this.isActive=!1,this.xa().setAttribute("aria-hidden","true"))};
g.k.Yu=function(a,b,c,d,e,f){return this.isCollapsed?!1:m3.prototype.Yu.call(this,a,b,c,d,e,f)};
g.k.ZG=function(a){this.I=!0;p3(this,500,a)};
g.k.YG=function(){this.I=!1;kxa(this)};
g.k.QG=function(a){a.stopPropagation();this.hide()};
g.k.SG=function(a){a.stopPropagation();q3(this);this.isCollapsed=!0;g.I(this.xa(),"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();m3.prototype.destroy.call(this)};g.t(s3,g.QN);g.k=s3.prototype;g.k.hd=function(a,b){if(!zxa(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.w1(b);c&&t3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Twa(this.o,b),x2(this.player)),!0}return null};
g.k.getOptions=function(){return zxa(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.rr=function(){if(this.B){var a=g.lN(this.player).getVideoContentRect(!0);g.Rh(this.B.element,a.width,a.height);g.Hh(this.B.element,a.left,a.top)}if(this.o){var b=this.player.Wk();a=this.o;b=b.width;g.K(a.B,"iv-drawer-small",426>=b);g.K(a.B,"iv-drawer-big",1280<=b)}};
g.k.QI=function(a){oxa(this,a.state);g.T(a.state,2)&&(this.on()&&this.EA()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Ru(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.F=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.lq(h)&&h.responseXML?h.responseXML:null)&&(t3(b,h),g.I(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.QN.prototype.load.call(this);oxa(this,g.lM(this.player));this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.tp()&&(a=rxa(this,a));var e={format:"XML",xe:a,onError:function(){b.F=null},
vf:{}};c.isPharma&&(e.vf.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.O().N.get(d);f&&sxa(e,f);f=f&&(f.kp||f.jp);if(!c.Vo||f)c.af?pxa(this,c.af,e):(this.A=function(){b.Na(e)},this.player.addEventListener("videodatachange",this.A));
g.CN(this.player,this.B.element,4);this.rr();(f=g.XB(c))&&xxa(this,f);(f=g.YB(c))&&f.featuredChannel&&yxa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Na=function(a){var b=this.player.getVideoData();b.af&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),pxa(this,b.af,a))};
g.k.unload=function(){g.uQ(this.player.app,"annotations_module",void 0);for(var a=g.p(Object.keys(this.G)),b=a.next();!b.done;b=a.next())this.G[b.value].destroy();this.I=null;this.o&&(this.o.destroy(),this.o=null,x2(this.player));this.M=!1;this.F&&(this.F.abort(),this.F=null);this.G={};this.u.hide();g.QN.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.k.DC=function(a){a===this.player.getVideoData().videoId&&(this.loaded?txa(this):this.load())};
g.k.on=function(){return!!this.o&&this.o.isAvailable()};
g.k.EA=function(){this.on();return!!this.o&&this.o.A};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.on();this.o&&(a?c?e3(this.o,c,b):e3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):f3(this.o))};
g.k.Ru=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.X=function(){this.player.O().N.unsubscribe("vast_info_card_add",this.DC,this);g.Fn(this.player.getRootNode(),g.bM.IV_DRAWER_OPEN);for(var a=this.N,b=0,c=a.length;b<c;b++)g.up(a[b]);this.N.length=0;g.QN.prototype.X.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.C(this,a);return a.element};g.aO.annotations_module=s3;g.aO.creatorendscreen=K2;})(_yt_player);
