(function(g){var window=this;var y3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.yz(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},z3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},Dxa=function(a,b){var c=new g.xz;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},Exa=function(){this.u=[];
this.o=[]},A3=function(a,b){switch(b.kind){case "asr":Fxa(b,a.u);
break;default:Fxa(b,a.o)}},Fxa=function(a,b){g.cb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},B3=function(){g.A.call(this);
this.u=new Exa;this.B=[]},C3=function(a,b,c){B3.call(this,a);
this.audioTrack=c;this.o=null;this.B=b.Zs},D3=function(){this.segments=[]},Gxa=function(a,b){var c=g.vb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.jb(a.segments,c),g.jb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.sb(a.segments,c,0,b),g.sb(a.segments,c+1,0,b)))},E3=function(a,b,c,d,e,f){g.A.call(this);
this.policy=a;this.player=b;this.N=c;this.F=d;this.C=e;this.I=f;this.M=this.player.O();this.B=new D3;this.u=this.A=this.o=null;this.G=new g.H(this.uA,1E3,this);this.events=new g.ds(this);g.C(this,this.G);g.C(this,this.events);this.events.L(b,"SEEK_COMPLETE",this.vC);this.vC();this.uA()},Hxa=function(a,b){var c=g.Iv(b,a.policy,{}).yc(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Gr(c,d,3,100).then(function(e){a.ha();var f=!(a.C?e.response:e.responseText)||400<=e.status,h=g.ww(e);h?(e=g.Iv(a.A,a.policy,{}),f=a.A,g.Ev(f.u,e,h),f.requestId=e.get("req_id"),Hxa(a,a.A)):(f||null==a.F||(h=a.A.o[0],a.C?a.F(e.response,1E3*(h.startTime+a.player.Kb())):a.F(e.responseText,1E3*(h.startTime+a.player.Kb()))),a.A=null,a.u=null)});
a.A=b;Gxa(a.B,a.A.o[0].u)},F3=function(a,b){B3.call(this,b.O());
this.ia=a;this.H=b;this.o=null;this.A=!1;this.C=g.Ly(this.H.O())&&!this.ia.u},Ixa=function(a,b){var c=[],d;
for(d in a.ia.o)if(a.ia.o.hasOwnProperty(d)){var e=a.ia.o[d];if(g.RN(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.xz({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Jxa=function(a,b){return null!=b&&b in a.ia.o?a.ia.o[b]:null},Kxa=function(a,b,c){var d=[],e;
for(e in a.ia.o)if(a.ia.o.hasOwnProperty(e)){var f=a.ia.o[e];if(g.RN(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},G3=function(a,b,c,d,e){B3.call(this,e||null);
this.videoId=b;this.Wz=d;this.C={};this.o=null;b=c||g.$p(a).hl||"";b=b.split("_").join("-");this.A=g.bq(a,{hl:b})},H3=function(a,b,c,d,e,f,h){var l={};
g.Ta(l,b);g.Ta(l,a.params);g.Ta(l,c);var m={};g.Ta(m,b.Nb);a.params.Nb&&g.Ta(m,a.params.Nb);g.Ta(m,c.Nb);l.Nb=m;g.U.call(this,{D:"div",J:"caption-window",P:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",J:"captions-text",P:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.U=!1;this.u=a;this.Y=this.T=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.F=null;this.maxWidth=.96*e;this.va=.96*f;this.o=l;this.Fa=
c;this.B=this.ca("captions-text");this.Ea=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Z=d/360*16;this.type=0;this.fa=this.Z*Lxa(m);a=new g.js(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.aJ,this);a.subscribe("dragmove",this.ZI,this);a.subscribe("dragend",this.YI,this);this.sa=this.na=0;b="";this.o.windowOpacity&&(a=g.v1(this.o.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.windowOpacity+
")");a={"background-color":b,display:!1===this.o.isVisible?"none":"","text-align":Mxa[this.o.textAlign]};this.Ea&&(a["border-radius"]=b?this.fa/8+"px":"");if(this.A=2===this.u.params.o||3===this.u.params.o)b=this.element,c="vertical-rl",1===this.o.A&&(c="vertical-lr"),g.le&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.zh(b,"-o-writing-mode",c),g.zh(b,"-webkit-writing-mode",c),g.zh(b,"writing-mode",c),g.zh(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.u.params.o&&(g.zh(b,"text-orientation",
""),g.zh(b,"transform","rotate(180deg)"));g.zh(this.element,a);switch(this.o.wf){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},Lxa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Nxa=function(a,b){var c={},d=b.background?b.background:a.o.Nb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.o.Nb.backgroundOpacity;d=g.v1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ea&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Z*Lxa(b)+"px";d=1;e=b.color||a.o.Nb.color;if(b.color||null!=b.textOpacity)e=g.v1(e),d=null==b.textOpacity?a.o.Nb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.jt&&(h=e=b.jt);var l=a.Z/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=r;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.hl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.Nb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Nf&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.qH&&(c.visibility="hidden");1===b.Tz&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Py||g.Qy,3===a.u.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.eg||2===b.eg||3===b.eg||4===b.eg||5===b.eg)if(g.Py)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.eg){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Oxa=function(a){a.F=g.se("SPAN");
g.zh(a.F,{display:"block"});g.I(a.F,"caption-visual-line");a.B.appendChild(a.F)},Pxa=function(a,b){var c=g.se("SPAN");
g.zh(c,{display:"inline-block","white-space":"pre-wrap"});g.zh(c,Nxa(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.zh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.zh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Qxa=function(a,b,c){a.U=a.U||!!c;
var d={};g.Ta(d,a.o.Nb);g.Ta(d,c||b.o);g.Ta(d,a.Fa.Nb);(c=!a.F)&&Oxa(a);for(var e=a.T&&a.Y&&g.Tb(d,a.Y)?a.T:Pxa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(Oxa(a),e=Pxa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.ue(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.Py||!g.Dh(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.Dh(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.ne?g.zh(e,m,"1em"):g.zh(e,m,"0.5em")))}a.Y=d;a.T=e;a.C.push(b)},I3=function(a,b,c,d,e,f,h){H3.call(this,a,b,c,d,e,f,h);
this.type=1},J3=function(a,b,c,d,e,f,h){H3.call(this,a,b,c,d,e,f,h);
this.type=2;this.G=[];this.N=this.I=this.aa=0;this.R=NaN;this.ya=0;this.za=null;this.ga=new g.H(this.aN,433,this);g.I(this.element,"ytp-caption-window-rollup");g.C(this,this.ga);g.zh(this.element,"overflow","hidden")},Rxa=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},Sxa=function(a){if(isNaN(a.R)){var b=a.o.ai;
if(b){var c=g.se("SPAN");g.Be(c,"\u2013".repeat(b));g.zh(c,Nxa(a,a.o.Nb));a.B.appendChild(c);a.R=c.offsetWidth;a.B.removeChild(c)}else a.R=0}return a.R},Txa=function(a,b){if(!b)return"";
a.A&&1!==a.u.params.A&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},Uxa=function(a){a.G=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.u,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.I=d;a.N=Math.max(Sxa(a),a.ya,Rxa(a,a.B))},Vxa=function(a,b){Uxa(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.I-c;if(c!==a.aa){var d=0<c&&0===a.aa;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),a.ga.kb());g.zh(a.B,"transform",Txa(a,c));a.aa=c}Uxa(a)},K3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.Xy.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=h},L3=function(a,b,c,d,e){g.Xy.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Wxa=function(a){var b="_"+M3++;
return new L3(0,0x8000000000000,0,b,a)},Yxa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.pc){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[q.getAttribute("p")];l=Xxa(l.textContent,n.textContent,q.textContent,f.textContent,h);return new K3(a,b,e,c,l,d,m)}switch(m.pc){case 9:case 10:m.eg=1;break;case 11:m.eg=2;break;case 12:m.eg=3;break;case 13:m.eg=4;break;case 14:m.eg=5}return new K3(a,b,e,c,l.textContent||"",d,m)},Xxa=function(a,b,c,d,e){var f=g.hl(),h=
f?g.se("DIV"):g.se("RUBY"),l=g.se("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.se("DIV"):g.se("RP");a.textContent=b;h.appendChild(a);b=f?g.se("DIV"):g.se("RT");b.textContent=c;h.appendChild(b);c=e.pc;if(10===c||11===c||12===c||13===c||14===c)if(g.zh(b,"text-emphasis-style","filled circle"),g.zh(b,"text-emphasis-color","currentcolor"),g.zh(b,"webkit-text-emphasis","filled circle"),11===e.pc||13===e.pc)g.zh(b,"webkit-text-emphasis-position","under left"),g.zh(b,"text-emphasis-position","under left");c=!0;if(4===e.pc||7===e.pc||12===e.pc||
14===e.pc)g.zh(h,"ruby-position","over"),g.zh(h,"-webkit-ruby-position","before");else if(5===e.pc||6===e.pc||11===e.pc||13===e.pc)g.zh(h,"ruby-position","under"),g.zh(h,"-webkit-ruby-position","after"),c=!1;e=f?g.se("DIV"):g.se("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.zh(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.zh(f,"display","none"),f=f.nextElementSibling,g.zh(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.zh(h.lastElementChild,"display","none"),d?(g.zh(h,"padding-top","0.6em"),g.zh(f,"top","0")):(g.zh(h,"padding-bottom","0.6em"),g.zh(f,"bottom","0")));return h},N3=function(){g.A.apply(this,arguments)},O3=function(a){N3.call(this);
this.F=a;this.B={};this.M={};this.N={};this.C="_"+M3++;this.I={};this.u=this.o=null;this.G=!0},P3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},Q3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},R3=function(a,b){var c=P3(a,b);
return void 0!==c?c:null},T3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return S3.test(c),c},Zxa=function(a,b){var c={},d=b.getAttribute("ws");
g.Ta(c,d?a.N[d]:a.F);d=R3(b,"mh");null!=d&&(c.sl=d);d=R3(b,"ju");null!=d&&(c.textAlign=d);d=R3(b,"pd");null!=d&&(c.o=d);d=R3(b,"sd");null!=d&&(c.A=d);d=T3(b,"wfc");null!=d&&(c.windowColor=d);d=P3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},$xa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ta(c,a.M[d]);d=R3(b,"ap");null!=d&&(c.wf=d);d=P3(b,"cc");null!=d&&(c.ai=d);d=P3(b,"ah");null!=d&&(c.Oe=d);d=P3(b,"rc");null!=d&&(c.u=d);d=P3(b,"av");null!=d&&(c.hg=d);return c},aya=function(a,b,c,d){var e={};
g.Ta(e,$xa(a,b));g.Ta(e,Zxa(a,b));d?g.Tb(e,a.F)?(d=a.C,e=a.F):d="_"+M3++:d=b.getAttribute("id")||"_"+M3++;a=P3(b,"t")+c;b=P3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.ai,e.ai=c;return new L3(a,b,0,d,e)},U3=function(a){N3.call(this);
this.F=a;this.o=new Map;this.B=new Map;this.C=new Map;this.u=new Map},V3=function(a){a=g.Rd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},bya=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.ai=b);if(2===f.o||3===f.o)b=f.u,f.u=f.ai,f.ai=b;return new L3(c,d,0,e,f)},X3=function(){this.A=this.time=this.mode=this.u=0;
this.B=new W3(this);this.C=new W3(this);this.o=[];this.clear()},dya=function(a,b,c){if(255===a&&255===b||!a&&!b)return{fj:a,
Xh:b,result:0};a=cya[a];b=cya[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Xh===d;if(d)return{fj:a,Xh:b,result:1}}else if(b&128&&1<=a&&31>=a)return{fj:a,Xh:b,result:2};return{fj:a,Xh:b,result:3}},fya=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,eya(a.B,b,c,d))},gya=function(a,b){a.o.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.p(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?fya(a,d.oy,d.py,b):1===d.type&&a.u&496&&eya(a.C,d.oy,d.py,b);a.o.length=0},Y3=function(){this.type=0},Z3=function(){this.state=this.Xh=this.fj=0},hya=function(){this.timestamp=this.o=0},$3=function(a){this.C=a;
this.A=[];this.o=this.u=this.row=0;this.style=new Y3;for(a=this.B=0;15>=a;a++){this.A[a]=[];for(var b=0;32>=b;b++)this.A[a][b]=new hya}},a4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var r=a.A[m][q];
if(0!==r.o){0===c&&(c=m,d=q);n=String.fromCharCode(r.o);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.o||32===q)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(q=a.A[h][m],r=q.o,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32===m||0===r)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},mya=function(a,b){switch(a){case 0:return iya[(b&127)-32];
case 1:return jya[b&15];case 2:return kya[b&31];case 3:return lya[b&31]}return 0},b4=function(a){return a.A[a.row][a.u]},c4=function(a,b,c){2<=b&&1<a.u&&(--a.u,b4(a).o=0);
var d=b4(a);d.timestamp=a.C.time+0;d.o=mya(b,c);32>a.u&&a.u++},nya=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.A[b+e][f],l=a.A[c+e][f];
h.o=l.o;h.timestamp=l.timestamp}},d4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},e4=function(a){a.row=0<a.o?a.o:1;
a.u=1;d4(a,0,15)},f4=function(a){this.A=a;
this.C=0;this.style=new Y3;this.F=new $3(this.A);this.G=new $3(this.A);this.text=new $3(this.A);this.u=this.F;this.B=this.G;this.o=this.u},g4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(a4(d,c),e4(a.u),e4(a.B),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.B;e?d.u=1:d.o!==b&&(d.o>b?(a4(d,c),d4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},oya=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.B},pya=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.A.mode=1<<a.o.B},W3=function(a){this.u=a;
this.C=0;this.A=new f4(this.u);this.F=new f4(this.u);this.o=new Z3;this.B=this.A},eya=function(a,b,c,d){a.o.update();
b=dya(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.fj;c=b.Xh;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&c4(a,0,b),c&96&&c4(a,0,c),0!==b&&0!==c&&3===a.style.type&&a4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.fj=e,b.Xh=c,b.state=2,b=e&8?a.F:a.A,a.B=b,a.u.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,h=1+d-c.o;nya(c,h,f,c.o);b=f;e=c.o;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));d4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:c4(b.o,0,32);break a;case 48:57===c?(d=b.o,b4(d).o=0,32>d.u&&d.u++):c4(b.o,1,c&15)}break;case 2:c&32&&c4(b.o,2,c&31);break;case 3:c&32&&c4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:oya(b);
break;case 33:d=b.o;1<d.u&&(--d.u,b4(d).o=0);break;case 36:d=b.o;b=b4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]===b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:g4(b,2,d);break;case 38:g4(b,3,d);break;case 39:g4(b,4,d);break;case 40:c4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.B;break;case 42:d=b.text;d.o=15;d.style.set(4);e4(d);pya(b);break;case 43:pya(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:a4(a,d)}d4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;a4(a,d);nya(a,b,b+1,a.o-1);d4(a,a.row,1)}break;case 46:d4(b.B,0,15);break;case 47:a4(b.u,d),b.B.updateTime(b.A.time+0),d=b.B,b.B=b.u,b.u=d,oya(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},qya=function(){},h4=function(a,b,c){this.I=a;
this.G=c;this.version=this.F=this.B=this.o=0;this.u=new DataView(this.I);this.A=[]},i4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},j4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},k4=function(a,b){N3.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.o=new X3;this.o.u=1<<this.track},l4=function(a){if("string"===typeof a)return!1;
a=new h4(a,8,0);return rya(a)},rya=function(a){if(!(a.o<a.u.byteLength)||1380139777!==j4(a))return!1;
a.version=i4(a);if(1<a.version)return!1;i4(a);i4(a);i4(a);return!0},m4=function(){N3.call(this)},sya=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Nf=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var q=h.childNodes[n];if(3===q.nodeType)q=new K3(b,c,d,e.id,q.nodeValue,f||0<n,g.Rb(l)?void 0:l),m.push(q),e.o.push(q);else{var r={};g.Ta(r,l);sya(a,b,c,d,e,!0,q,r,m)}}},n4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},tya=function(a,b,c,d){d=Object.assign({sl:0},d);
return new L3(a,b,c,"_"+M3++,d)},o4=function(a){g.A.call(this);
this.u=a;this.o=null},vya=function(a){var b={};
if(a=z3(a))b.lang=a,uya.test(a)&&(b.o=1);return b},r4=function(a){g.QN.call(this,a);
this.H=a;this.A=this.H.O();this.videoData=this.H.getVideoData();this.va=g.lN(this.H);this.B={Nb:{}};this.F={Nb:{}};this.R=[];this.M={};this.da={};this.T=!1;this.na=g.SN(this.videoData,this.H);this.ya=!!this.videoData.captionTracks.length;this.za=!!this.videoData.om;this.fa="3"===this.A.controlsType;this.u=this.G=this.I=this.aa=this.ra=null;this.ga=new o4(this.A);this.o=null;this.Y=new g.ds(this);var b=null,c=g.lo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Wn(c));this.storage=b;b=
a.app.C;c=!(!b||!b.lo());this.sa=!(!b||!b.rk());this.C=this.fa&&c&&!this.na;this.N=!this.C&&this.fa&&this.sa&&this.na;g.C(this,this.ga);this.C?this.Z=this.U=null:(this.U=new g.wn(this.dE,void 0,this),g.C(this,this.U),this.Z=new g.H(this.yO,2E3,this),g.C(this,this.Z));g.C(this,this.Y);this.C||this.Y.L(a,"resize",this.Uw);this.Y.L(a,"onPlaybackAudioChange",this.QK);this.Y.L(a,g.$y("captions"),this.bJ,this);this.Y.L(a,"crx_captions",this.cJ,this);p4(this,q4(this,"display-settings")||{})},s4=function(a){if(1===
a.A.Zh||1===a.videoData.Zh||"alwayson"===g.PB(a.videoData,"yt:cc"))return!0;
if(2===a.A.Zh){var b=q4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().gt;return"ON"===c||"on"===g.PB(a.videoData,"yt:cc")},t4=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Gp||"FORCED_ON"===c.gt},v4=function(a,b){if(a.u){if(a.G&&a.G.o)return a.G.o;
var c=b;c||(c=a.za?!1:a.ya?!1:!0);c=a.u.yj(c);for(var d=[a.videoData.captionsLanguagePreference,a.A.captionsLanguagePreference,g.PB(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(z3(c[f])===d[e])return c[f];return a.G&&a.G.At?a.G.At:(d=c.find(function(h){return h.isDefault}))?d:c[0]||u4(a)}return null},u4=function(a){return a.G&&a.G.Gp},w4=function(a){var b=u4(a);
return!!b&&a.o===b},wya=function(a,b){for(var c=a.H.app.C.xa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},y4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.T=c,a.T&&x4(a,"module-enabled",!!b));a.o=b;t4(a)&&(a.o=u4(a));a.load()},xya=function(a,b){var c=a.va.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&uya.test(d)&&(b.params.o=1);d=a.va.getPlayerSize();switch(null!=b.params.sl?b.params.sl:1<b.o.length?1:0){case 1:return new I3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);case 2:return new J3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);default:return new H3(b,a.B,a.F,c,d.width,d.height,a.A.experiments)}},p4=function(a,b,c){c=void 0===c?!1:c;
var d=z4.Nb;a.B={};g.Ta(a.B,z4);a.B.Nb={};g.Ta(a.B.Nb,d);a.F={Nb:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;S3.test(f);e.Nb.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;S3.test(f);e.Nb.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||z4.windowColor;S3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Nb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Nb.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Nf?3:d.bold?1:d.Nf?2:0);f=f.Nb;switch(e){case 1:f.bold=!0;delete f.Nf;break;case 2:delete f.bold;f.Nf=!0;break;case 3:f.bold=!0;f.Nf=!0;break;default:delete f.bold,delete f.Nf}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Nb.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=z4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Nb.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Nb.fontFamily=f;a.loaded&&a.Uw();c&&x4(a,"display-settings",b)},zya=function(a,b){if(b&&!a.I){var c=Wxa({o:0,
lang:"en"});a.I=[c,new K3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.yN(a.player,a.I)}else!b&&a.I&&(yya(a,a.I),a.I=null)},yya=function(a,b){g.BU(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.lb(this.R,c)},a);
a.U.kb()},q4=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},x4=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.zC.prototype.qm=g.ca(11,function(){for(var a=g.ee(document,"track",void 0,this.o),b=0;b<a.length;b++)g.xe(a[b])});
g.uL.prototype.qm=g.ca(10,function(){this.o.qm()});
g.zC.prototype.lo=g.ca(9,function(){return!!this.o.textTracks});
g.uL.prototype.lo=g.ca(8,function(){return this.o.lo()});
g.zC.prototype.km=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.uL.prototype.km=g.ca(6,function(a){this.o.km(a)});
g.qC.prototype.rk=g.ca(5,function(){});
g.zC.prototype.rk=g.ca(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.uL.prototype.rk=g.ca(3,function(){return this.o.rk()});
g.jt.prototype.Vp=g.ca(1,function(a){return(a=this.sg(a))?a.o:0});
g.ow.prototype.Vp=g.ca(0,function(){return 0});
var uya=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;Exa.prototype.yj=function(a){return a?this.o.concat(this.u):this.o};
g.t(B3,g.A);g.k=B3.prototype;g.k.yj=function(a){return this.u.yj(a)};
g.k.zq=function(){};
g.k.Aq=function(){};
g.k.Oh=function(){};
g.k.Vk=function(){return""};
g.k.RC=function(){return!1};
g.k.X=function(){this.Oh();g.A.prototype.X.call(this)};
g.t(C3,B3);C3.prototype.zq=function(a,b,c){var d=this;this.ha();b=this.Vk(a,b);this.Oh();this.o=g.rq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
C3.prototype.Aq=function(a){if(this.audioTrack)for(var b=g.p(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())A3(this.u,c.value);a()};
C3.prototype.Vk=function(a,b){var c=a.yc(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.hl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=z3(a));return g.bq(c,d)};
C3.prototype.Oh=function(){this.o&&this.o.abort()};
D3.prototype.contains=function(a){a=g.vb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
D3.prototype.length=function(){return this.segments.length/2};
g.t(E3,g.A);g.k=E3.prototype;g.k.X=function(){g.A.prototype.X.call(this);this.u&&this.u.cancel()};
g.k.vC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Kb();var b=this.o;this.o=g.ab(this.N.ph(a).o);b!==this.o&&this.I&&this.I()};
g.k.reset=function(){this.B=new D3;this.u&&(this.u.cancel(),this.u=null)};
g.k.uA=function(){this.ha();var a;if(a=null!=this.o)a=this.o,a=a.o.Gh(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.ji(),a.o[0].duration?(this.B.contains(a.o[0].u)||Hxa(this,a),this.o=g.ab(a.o)):!g.Q(this.M.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.C&&this.o.C+this.player.Kb()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.G.start()};
g.t(F3,B3);g.k=F3.prototype;g.k.zq=function(a,b,c){var d=this;this.Oh();b=Jxa(this,a.getId());b||(b=a.languageCode,b=this.ia.u?Kxa(this,b,"386"):Kxa(this,b));if(b){var e=1E3*(b.index.Vp(b.index.Hf())-b.index.Ad(b.index.Hf()));this.o=new E3(new g.$u,this.H,b,function(f,h){c(f,a,h,e)},this.C||g.Qu(b.info),function(){d.o&&d.o.reset();
d.A=!0})}};
g.k.RC=function(){var a=this.A;this.A=!1;return a};
g.k.Aq=function(a){var b;this.C?b=[new g.xz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.xz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ia.u?Ixa(this,"386"):Ixa(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())A3(this.u,c.value);a()};
g.k.Oh=function(){this.o&&(this.o.dispose(),this.o=null)};
g.k.Vk=function(){return""};
g.t(G3,B3);G3.prototype.zq=function(a,b,c){var d=this;this.ha();b=this.Vk(a,b);this.Oh();this.o=g.rq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
G3.prototype.Aq=function(a){var b=this,c=this.A,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.Wz&&(d.asrs=1);c=g.bq(c,d);this.Oh();this.o=g.rq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),q=l.getAttribute("name"),r=l.getAttribute("kind"),u=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),B="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");A3(b.u,new g.xz({languageCode:m,languageName:n,name:q,kind:r,id:u,is_servable:!0,is_translateable:B,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.C[m.languageCode]=m.languageName,b.B.push(m)}a()},
withCredentials:!0})};
G3.prototype.Vk=function(a,b){var c=this.A,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=z3(a));return c=g.bq(c,d)};
G3.prototype.Oh=function(){this.o&&this.o.abort()};
var S3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Mxa=["left","right","center","justify"];g.t(H3,g.U);g.k=H3.prototype;g.k.aJ=function(a,b){var c=g.Ph(this.element,this.element.parentElement);this.na=a-c.x;this.sa=b-c.y;g.I(this.element,"ytp-dragging")};
g.k.ZI=function(a,b){var c=g.Sh(this.element),d=a-this.na-.02*this.playerWidth,e=b-this.sa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Rd(f,0,2));var h=(e+c.height/2)/this.va*3;h=Math.floor(g.Rd(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Rd(d,0,1);c=(e+h/2*c.height)/this.va;c=100*g.Rd(c,0,1);this.u.params.wf=l;this.u.params.hg=c;this.u.params.Oe=d;this.o.wf=l;this.o.hg=c;this.o.Oe=d;this.uD()};
g.k.YI=function(){g.Fn(this.element,"ytp-dragging")};
g.k.uD=function(){this.nk(this.C)};
g.k.nk=function(a){var b=Math.min(this.mz(),this.maxWidth),c=this.lz(),d="";3===this.u.params.o&&(d="rotate(180deg)");g.zh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Ts(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.o.Oe+2;d=this.o.wf;switch(d){case 0:case 3:case 6:b=this.o.Nb.fontSizeIncrement;!g.Q(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.o.o&&3!==this.o.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.o.hg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.zh(this.element,a)};
g.k.Ts=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.U||this.C.length>b)b=0,this.U=!1,this.C=[],this.F=this.Y=this.T=null,g.ve(this.B);for(;b<a.length;b++)Qxa(this,a[b])};
g.k.mz=function(){return 0};
g.k.lz=function(){return 0};
g.k.toString=function(){return g.U.prototype.toString.call(this)};g.t(I3,H3);I3.prototype.Ts=function(a){var b=this.u.o;H3.prototype.Ts.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Ta(d,c.o);g.Ta(d,Aya);var e=c.o;var f=d}Qxa(this,c,d)}};
var Aya={qH:!0};g.t(J3,H3);g.k=J3.prototype;g.k.uD=function(){g.zn(this.ga)};
g.k.aN=function(){g.Fn(this.element,"ytp-rollup-mode");this.nk(this.za,!0)};
g.k.lz=function(){return this.A?this.N:this.I};
g.k.mz=function(){return this.A?this.I:this.N};
g.k.nk=function(a,b){this.za=a;if(this.u.params.u){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.ya=this.N;this.I=this.N=0;H3.prototype.nk.call(this,a);Vxa(this,b);H3.prototype.nk.call(this,a)}else H3.prototype.nk.call(this,a)};g.t(K3,g.Xy);K3.prototype.toString=function(){return g.Xy.prototype.toString.call(this)};g.t(L3,g.Xy);L3.prototype.toString=function(){return g.Xy.prototype.toString.call(this)};
var M3=0;g.t(N3,g.A);N3.prototype.A=function(){return[]};
N3.prototype.reset=function(){};g.t(O3,N3);O3.prototype.reset=function(){this.I={};this.u=this.o=null;this.G=!0};
O3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.B,l={},m=c.getAttribute("p");m&&g.Ta(l,this.B[m]);m=Q3(c,"b");null!=m&&
(l.bold=m);m=Q3(c,"i");null!=m&&(l.Nf=m);m=Q3(c,"u");null!=m&&(l.underline=m);m=R3(c,"et");null!=m&&(l.charEdgeStyle=m);m=R3(c,"of");null!=m&&(l.offset=m);m=T3(c,"bc");null!=m&&(l.background=m);m=T3(c,"ec");null!=m&&(l.jt=m);m=T3(c,"fc");null!=m&&(l.color=m);m=R3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=P3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=P3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=P3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=R3(c,"rb");null!=m&&10!==m&&0!==m&&(l.pc=
10<m?m-1:m);c=R3(c,"hg");null!=c&&(l.Tz=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.N[d]=Zxa(this,c);break;case "wp":d=c.getAttribute("id"),this.M[d]=$xa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=aya(this,d,e,!1);(d=this.I[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.I[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.C;m=!!Q3(d,
"a");n=(P3(d,"t")||0)+n;var q=P3(d,"d")||5E3;m||(!this.G&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var r=m?6:5,u=d.getAttribute("p");u=u?this.B[u]:null;var w=Array.from(d.childNodes);w.length&&(this.G=null!=d.getAttribute("d"));for(var B=0;B<w.length;B++){var z=w[B],D=void 0;0<B&&(m=!0);var F=void 0;1===z.nodeType&&(F=z);if(F&&"s"===F.tagName){if((z=(z=F.getAttribute("p"))?this.B[z]:null)&&z.pc&&(1===z.pc?(z=w.slice(B,B+4),4===z.length&&
(D=Yxa(n,q,l,m,r,z,this.B),B+=3)):D=Yxa(n,q,l,m,r,[F],this.B)),!D){var G=F;D=n;F=q;z=l;var V=m,J=r,wb=G.textContent?G.textContent:"",Hb=G.getAttribute("p");Hb=Hb?this.B[Hb]:null;G=P3(G,"t")||0;D=new K3(D+G,F-G,J,z,wb,V,Hb)}}else D=new K3(n,q,r,l,z.textContent||"",m,u);h.push(D);this.u=D}if(0<h.length)for(h[0].windowId===this.C&&(this.o=aya(this,d,e,!0),c.push(this.o)),d=g.p(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.o.id,this.o.o.push(h),c.push(h)}e=c}else e=[];return e};var Bya=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.t(U3,N3);U3.prototype.reset=function(){this.u.clear()};
U3.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.o.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.Nf=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.jt=V3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=V3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=V3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.pc=10<l?l-1:l,h.eg=Bya.get(h.pc));f.hgHorizGroup&&(h.Tz=f.hgHorizGroup);this.o.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.C.get(l)):Object.assign(h,
this.F),void 0!==f.mhModeHint&&(h.sl=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.A=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=V3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.B.get(l)),void 0!==f.ahHorPos&&
(h.Oe=f.ahHorPos),void 0!==f.apPoint&&(h.wf=f.apPoint),void 0!==f.avVerPos&&(h.hg=f.avVerPos),void 0!==f.ccCols&&(h.ai=f.ccCols),void 0!==f.rcRows&&(h.u=f.rcRows),this.B.set(d++,h);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=bya(this,m,e,f,h),d.push(e),this.u.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+M3++,l=bya(this,m,e,f,h),d.push(l),this.u.set(h,l));0===f&&(f=5E3);l=this.u.get(h);var n=
!!m.aAppend,q=n?6:5,r=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],B=w.utf8;if(B){var z=w.tOffsetMs||0,D=null;w.pPenId&&(D=this.o.get(w.pPenId));if(2===(null!=l.params.sl?l.params.sl:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(w=D&&1===D.pc)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var F=r[w+1].pPenId;(F=this.o.get(F))&&F.pc&&2===F.pc?(F=r[w+2].pPenId,F=this.o.get(F),!F||!F.pc||3>F.pc?w=!1:(F=r[w+3].pPenId,w=(F=this.o.get(F))&&
F.pc&&2===F.pc?!0:!1)):w=!1}if(w){z=r[m+1].utf8;w=r[m+3].utf8;F=r[m+2].utf8;var G=this.o.get(r[m+2].pPenId);B=Xxa(B,z,F,w,G);n=new K3(e,f,q,h,B,n,D);m+=3}else n=new K3(e+z,f-z,q,l.id,B,n,D||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};X3.prototype.clear=function(){this.A=this.time=this.mode=0;this.o=[];this.reset()};
X3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var cya=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Y3.prototype.set=function(a){this.type=a};
Y3.prototype.get=function(){return this.type};
Z3.prototype.clear=function(){this.state=0};
Z3.prototype.update=function(){this.state=2===this.state?1:0};
Z3.prototype.isValid=function(){return 0!==this.state};
Z3.prototype.matches=function(a,b){return this.isValid()&&a===this.fj&&b===this.Xh};
hya.prototype.reset=function(){this.timestamp=this.o=0};
$3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
$3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
$3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.o=0;this.u=this.row=1};
var iya=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],jya=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],kya=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],lya=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];f4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.u=this.F;this.B=this.G;this.o=this.u;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
W3.prototype.reset=function(a){this.C=a;this.o.clear();this.B=this.A;this.A.reset(a,0);this.F.reset(a,1)};qya.prototype.C=function(){};g.t(h4,qya);h4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+M3++;c=c/1E3-this.G;d=d/1E3-this.G;a=new L3(c,d-c,5,f,{textAlign:0,wf:0,Oe:2.5*b,hg:5.33*a});e=new K3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.t(k4,N3);k4.prototype.A=function(a){a=new h4(a,a.byteLength,this.u);if(rya(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.B=j4(a)*(1E3/45):1===a.version&&(a.B=4294967296*j4(a)+j4(a)),a.F=i4(a);0<a.F;a.F--){var b=i4(a),c=i4(a),d=i4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,oy:c,py:d,order:b.o.length}))}gya(this.o,a);return a.A}return[]};
k4.prototype.reset=function(){this.o.clear()};g.t(m4,N3);
m4.prototype.A=function(a,b){for(var c=[],d=a.split(Cya),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!Dya.test(f)){var l=A4.exec(f);if(l&&4<=l.length){var m=n4(l[1]),n=n4(l[2])-m;m+=h;var q=(l=l[3])?l.split(" "):[];l={};var r=null,u="",w=null,B="";l.textAlign=2;q=g.p(q);for(var z=q.next();!z.done;z=q.next())if(z=z.value.split(":"),2===z.length){var D=z[1];switch(z[0]){case "line":z=D.split(",");z[0].endsWith("%")&&(r=z[0],l.hg=Number.parseInt(r,10),2===z.length&&(u=z[1].trim()));break;case "position":z=
D.split(",");w=z[0];l.Oe=Number.parseInt(w,10);2===z.length&&(B=z[1].trim());break;case "align":switch(D){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.hg=100,u||(u="end"));if(!w)switch(l.textAlign){case 0:l.Oe=0;break;case 1:l.Oe=100;break;default:l.Oe=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(B){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.wf=0>r||8<r?7:r;f=f.substring(A4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");B=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=tya(m,n,5,B),n=new K3(m,n,5,h.id,l,!1,g.Rb(f)?void 0:f),c.push(h),c.push(n),h.o.push(n);else for(u=l.split(Eya),1===u.length?(l=5,B=tya(m,n,l,B)):(r=l=6,B=Object.assign({ai:32},B),B=new L3(m,n,r,"_"+M3++,B)),c.push(B),r=m,w=0;w<u.length;w++)q=u[w],0===w%2?(z=g.w1("<html>"+q+"</html>"),z.getElementsByTagName("parsererror").length?
(D=z.createElement("span"),D.appendChild(z.createTextNode(q))):D=z.firstChild,sya(this,r,n-(r-m),l,B,0<w,D,f,c)):r=n4(q)+h}A4.lastIndex=0}}return c};
var Dya=/^NOTE/,Cya=/(?:\r\n|\r|\n){2,}/,A4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Eya=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(o4,g.A);o4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
o4.prototype.reset=function(){this.o&&this.o.reset()};
o4.prototype.X=function(){g.A.prototype.X.call(this);this.clear()};var z4={windowColor:"#080808",windowOpacity:0,textAlign:2,wf:7,Oe:50,hg:100,Nb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(r4,g.QN);g.k=r4.prototype;g.k.X=function(){if(this.C||this.N){var a=this.H.app.C;a&&!a.ha()&&a.qm()}else zya(this,!1);g.QN.prototype.X.call(this)};
g.k.load=function(){var a=this;g.QN.prototype.load.call(this);var b=!g.Q(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.G=this.player.getAudioTrack();if(this.u)this.o&&(this.ga.clear(),this.C?wya(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.zq(this.o,"json3",function(d,e,f,h){if(d){a.u.RC()&&(a.R=[],g.uQ(a.H.app,"captions",void 0),a.U.kb(),a.ga.reset());var l=a.ga;f=f||0;h=h||0;if(l.u.ea("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.Bt(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),l4(d)||(d=g.dg(new Uint8Array(d))))}}else"string"===typeof d||l4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.Bt(m,0,1835295092))&&m.size?g.dg(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,q=f,r=h;if(!l4(n))throw Error("Invalid binary caption track data");l.o||(l.o=new k4(r,e));var u=l.o.A(n,q)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.o||(l.o=new m4),q=l.o.A(e,r),.01>Math.random()&&g.qr(Error("Deprecated subtitles format in web player: WebVTT")),n=q;else b:{q=d;if("{"===q[0])try{l.o||(l.o=new U3(vya(e)));n=l.o.A(q,f);break b}catch(G){g.pr(G);n=[];break b}r=g.w1(q);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=q;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.o||(l.o=new O3(vya(e),l.u));n=l.o.A(r,f);break b}var B=Error("Unsupported subtitles format in web player (Format2)");
B.params=q;throw B;}if("transcript"===r.firstChild.tagName){var z=Error("Unsupported subtitles format in web player (Format1)");z.params=q;throw z;}var D=Error("Invalid caption track data");D.params=q;throw D;}u=n}var F=u}catch(G){g.pr(G),l.clear(),F=[]}else F=[];g.yN(a.player,F);!a.T||a.N||w4(a)||g.zy(a.A)||g.Ay(a.A)||(a.Z.Ff(),F=Wxa({wf:0,Oe:5,hg:5,u:2,textAlign:0,o:0,lang:"en"}),a.aa=[F],l=["Click "," for settings"],a.ra||(u=new g.YL(g.KM()),g.C(a,u),a.ra=u.element),u=F.end-F.start,(e=g.yz(a.o))&&
a.aa.push(new K3(F.start,u,0,F.id,e)),a.aa.push(new K3(F.start,u,0,F.id,l[0]),new K3(F.start,u,0,F.id,a.ra,!0),new K3(F.start,u,0,F.id,l[1],!0)),g.yN(a.player,a.aa),a.Z.kb());!a.T||a.N||w4(a)||(x4(a,"module-enabled",!0),a.G&&(a.G.o=a.o),(F=g.W(a.player.app))&&g.UI(F.G));a.T=!1}}),!b||this.C||this.N||w4(this)||this.player.oa("captionschanged",y3(this.o))),b||(this.o&&!w4(this)?this.player.oa("captionschanged",y3(this.o)):this.player.oa("onCaptionsTrackListChanged"));
else{var c;this.na?c=new F3(this.videoData.ia,this.player):this.ya?c=new C3(this.A,this.videoData,this.player.getAudioTrack()):c=new G3(this.videoData.om,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.A.captionsLanguagePreference||g.PB(this.videoData,"yt:cc_default_lang")||this.A.ee,this.videoData.ct,this.A);this.u=c;g.C(this,this.u);c.Aq(function(){var d;a.T||s4(a)?d=v4(a,a.T):t4(a)&&(d=u4(a));if(a.C||a.N){for(var e=a.u.yj(!0),f=[],h=0;h<e.length;h++){var l=e[h],m=g.re("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.yz(l));m.setAttribute("srclang",z3(l));m.setAttribute("id",l.toString());a.N||m.setAttribute("src",a.u.Vk(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.H.app.C;d.km(f);f=d.xa();a.sa&&a.Y.L(f.textTracks,"change",a.DN)}else!a.o&&d&&y4(a,d),a.player.oa("onCaptionsTrackListChanged"),a.player.oa("onApiChange")})}};
g.k.unload=function(){this.C&&this.o?wya(this,!1):(this.Z&&this.Z.Ff(),g.uQ(this.player.app,"captions",void 0),this.R=[],this.u&&this.u.Oh(),this.ga.clear(),this.I&&g.yN(this.player,this.I),this.Uw());g.QN.prototype.unload.call(this);var a=g.W(this.player.app);a&&g.UI(a.G);this.player.oa("captionschanged",{})};
g.k.create=function(){(this.fa?this.C||this.N:t4(this)||s4(this))&&this.load()};
g.k.getTrackById=function(a){for(var b=this.u.yj(!0),c=0;c<b.length;c++)if(b[c].toString()===a)return b[c];return null};
g.k.DN=function(){for(var a=this.H.app.C.xa().textTracks,b=null,c=0;c<a.length;c++)"showing"===a[c].mode&&(b=this.getTrackById(a[c].id));(this.loaded?this.o:null)!==b&&y4(this,b,!0)};
g.k.kP=function(){!this.o&&this.C||this.unload()};
g.k.bJ=function(a){this.R.push(a);this.U.kb()};
g.k.cJ=function(a){g.lb(this.R,a);this.u instanceof F3&&this.u.C&&g.BU(this.player.app,[a],void 0);this.U.kb()};
g.k.rO=function(a){if(a instanceof L3){var b=this.M[a.id];b&&b.u!==a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=xya(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.da[b]||(this.da[b]=[]),this.da[b].push(a)};
g.k.yO=function(){yya(this,this.aa);this.aa=null};
g.k.dE=function(){var a=this;this.U.stop();g.Sb(this.da);this.R.sort(g.Zy);var b=this.R;if(this.I){var c=(0,g.ye)(b,function(d){return-1===this.I.indexOf(d)},this);
c.length&&(b=c)}(0,g.y)(b,this.rO,this);g.Cb(this.M,function(d,e){a.da[e]?(d.element.parentNode||(d instanceof J3||d instanceof I3||g.Fb(a.M,function(f,h){h!==e&&f.u.params.wf===d.u.params.wf&&f.u.params.Oe===d.u.params.Oe&&f.u.params.hg===d.u.params.hg&&(f.dispose(),delete a.M[h]);return h===e},a),g.CN(a.player,d.element,4)),d.nk(a.da[e])):(d.dispose(),delete a.M[e])},this)};
g.k.EO=function(){p4(this,{},!0);g.Q(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.oa("captionssettingschanged")};
g.k.JG=function(){var a=z4.Nb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Nf?3:a.bold?1:a.Nf?2:0,textOpacity:a.textOpacity,windowColor:z4.windowColor,windowOpacity:z4.windowOpacity};var b=q4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.lE=function(a,b){var c={};g.Ta(c,q4(this,"display-settings"));g.Ta(c,a);p4(this,c,b);this.player.oa("captionssettingschanged")};
g.k.Uw=function(){!this.C&&this.loaded&&(g.Cb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.dE())};
g.k.hd=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Rd(b,-2,4);this.lE({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&y4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.A.A&&x4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Pa(b))break;if(g.Rb(b)){y4(this,null,!0);break}for(var d=this.u.yj(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
Dxa(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||y4(this,c,!0)}else return this.loaded&&this.o&&!w4(this)?y3(this.o):{};return"";case "tracklist":return this.u?(0,g.Ic)(this.u.yj(!(!b||!b.includeAsr)),function(h){return y3(h)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.C||void 0===b||zya(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.A&&a.push("stickyLoading");return a};
g.k.UH=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.k.dP=function(){this.loaded&&this.o&&!w4(this)?(x4(this,"module-enabled",!1),this.unload(),t4(this,!0)&&y4(this,u4(this),!1)):y4(this,w4(this)||!this.o?v4(this,!0):this.o,!0)};
g.k.QK=function(){var a=w4(this);t4(this,a)?y4(this,this.player.getAudioTrack().Gp,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.fa?this.C||this.N:t4(this)||s4(this))&&(a?y4(this,v4(this),!1):this.load()))};g.aO.captions=r4;})(_yt_player);
